In [1]:
import pandas as pd
import numpy as np
from matplotlib import pylab as mat

Importing the Data set

In [2]:
df = pd.read_csv("List of Countries by Sugarcane Production.csv")

In [3]:
df.head()

,Unnamed: 0,Country,Continent,Production (Tons),Production per Person (Kg),Acreage (Hectare),Yield (Kg / Hectare)
0,0,Brazil,South America,768.678.382,"3.668,531",10.226.205,"75.167,5"
1,1,India,Asia,348.448.000,260721,4.950.000,"70.393,5"
2,2,China,Asia,123.059.739,88287,1.675.215,"73.459,1"
3,3,Thailand,Asia,87.468.496,"1.264,303",1.336.575,"65.442,2"
4,4,Pakistan,Asia,65.450.704,324219,1.130.820,57.879

Total number of unique countries in the data set

In [4]:
len(df["Country"].unique())

103

Cleaning the data

In [5]:
df["Production (Tons)"] = df["Production (Tons)"].str.replace(".","") # removing the "." in the production values


df["Production per Person (Kg)"] = df["Production per Person (Kg)"].str.replace(".","").str.replace(",",".")
#replacing the "," in the production per person values with "." first and then replacing all "." with empty string


df["Acreage (Hectare)"] = df["Acreage (Hectare)"].str.replace(".","") # removing the "." in the Acreage values


df["Yield (Kg / Hectare)"]= df["Yield (Kg / Hectare)"].str.replace(".","").str.replace(",",".")
#replacing the "," in the Yield column values with "." first and then replacing all "." with empty string

In [6]:
df.head()

,Unnamed: 0,Country,Continent,Production (Tons),Production per Person (Kg),Acreage (Hectare),Yield (Kg / Hectare)
0,0,Brazil,South America,768678382,3668.531,10226205,75167.5
1,1,India,Asia,348448000,260721,4950000,70393.5
2,2,China,Asia,123059739,88287,1675215,73459.1
3,3,Thailand,Asia,87468496,1264.303,1336575,65442.2
4,4,Pakistan,Asia,65450704,324219,1130820,57879

Changing the column names for better accessibility

In [7]:
df.rename(columns= {"Production (Tons)": "Production(Tons)"}, inplace = True)

df.rename(columns= {"Production per Person (Kg)": "Production_per_person(Kg)"}, inplace = True)

df.rename(columns= {"Acreage (Hectare)": "Acreage(Hectare)"}, inplace = True)

df.rename(columns= {"Yield (Kg / Hectare)": "Yield(Kg/Hectare)"}, inplace = True)

In [8]:
df.head()

,Unnamed: 0,Country,Continent,Production(Tons),Production_per_person(Kg),Acreage(Hectare),Yield(Kg/Hectare)
0,0,Brazil,South America,768678382,3668.531,10226205,75167.5
1,1,India,Asia,348448000,260721,4950000,70393.5
2,2,China,Asia,123059739,88287,1675215,73459.1
3,3,Thailand,Asia,87468496,1264.303,1336575,65442.2
4,4,Pakistan,Asia,65450704,324219,1130820,57879

Removing the NaN values

In [9]:
df.isna().sum() # listing the NaN values

Unnamed: 0                   0
Country                      0
Continent                    0
Production(Tons)             0
Production_per_person(Kg)    0
Acreage(Hectare)             1
Yield(Kg/Hectare)            1
dtype: int64

In [10]:
df[df["Acreage(Hectare)"].isnull()]

,Unnamed: 0,Country,Continent,Production(Tons),Production_per_person(Kg),Acreage(Hectare),Yield(Kg/Hectare)
99,99,Djibouti,Africa,53,51,NaN,NaN

In [11]:
df = df.dropna().reset_index().drop("index", axis = 1) # Removing all the NaN values

In [12]:

df  # as you can see , the row with NaN value is removed

,Unnamed: 0,Country,Continent,Production(Tons),Production_per_person(Kg),Acreage(Hectare),Yield(Kg/Hectare)
0,0,Brazil,South America,768678382,3668.531,10226205,75167.5
1,1,India,Asia,348448000,260721,4950000,70393.5
2,2,China,Asia,123059739,88287,1675215,73459.1
3,3,Thailand,Asia,87468496,1264.303,1336575,65442.2
4,4,Pakistan,Asia,65450704,324219,1130820,57879
...,...,...,...,...,...,...,...
97,97,Spain,Europe,394,8,9,43596.5
98,98,Lebanon,Asia,97,16,3,28386.4
99,100,Singapore,Asia,50,9,2,25
100,101,Samoa,Oceania,12,6,1,11949.8
101,102,Syria,Asia,1,0,0,83034.2

In [13]:
df.nunique()

Unnamed: 0                   102
Country                      102
Continent                      6
Production(Tons)             102
Production_per_person(Kg)    101
Acreage(Hectare)             101
Yield(Kg/Hectare)            102
dtype: int64

Managing the Data-type of the attributes

In [14]:
df.dtypes

Unnamed: 0                    int64
Country                      object
Continent                    object
Production(Tons)             object
Production_per_person(Kg)    object
Acreage(Hectare)             object
Yield(Kg/Hectare)            object
dtype: object

In [15]:
df["Production(Tons)"] = df["Production(Tons)"].astype(float)  # changing the data-type of "production" column to float


df["Production_per_person(Kg)"] = df["Production_per_person(Kg)"].astype(float)  # changing the data-type of "production per person" column to float


df["Acreage(Hectare)"] = df["Acreage(Hectare)"].astype(float)  # changing the data-type of "Acreage" column to float


df["Yield(Kg/Hectare)"] = df["Yield(Kg/Hectare)"].astype(float)  # changing the data-type of "Yield" column to float

In [16]:
df.dtypes

Unnamed: 0                     int64
Country                       object
Continent                     object
Production(Tons)             float64
Production_per_person(Kg)    float64
Acreage(Hectare)             float64
Yield(Kg/Hectare)            float64
dtype: object

In [17]:
df.head()

,Unnamed: 0,Country,Continent,Production(Tons),Production_per_person(Kg),Acreage(Hectare),Yield(Kg/Hectare)
0,0,Brazil,South America,768678382.0,3668.531,10226205.0,75167.5
1,1,India,Asia,348448000.0,260721.000,4950000.0,70393.5
2,2,China,Asia,123059739.0,88287.000,1675215.0,73459.1
3,3,Thailand,Asia,87468496.0,1264.303,1336575.0,65442.2
4,4,Pakistan,Asia,65450704.0,324219.000,1130820.0,57879.0

Exporting the Cleaned data to a new csv file

In [18]:
file = open("cleaned_sugarcane_data.csv",'a')

In [19]:
df.to_csv("cleaned_sugarcane_data.csv",index=False)

In [20]:
x = pd.read_csv("cleaned_sugarcane_data.csv")

In [21]:
x.head()

,Unnamed: 0,Country,Continent,Production(Tons),Production_per_person(Kg),Acreage(Hectare),Yield(Kg/Hectare)
0,0,Brazil,South America,768678382.0,3668.531,10226205.0,75167.5
1,1,India,Asia,348448000.0,260721.000,4950000.0,70393.5
2,2,China,Asia,123059739.0,88287.000,1675215.0,73459.1
3,3,Thailand,Asia,87468496.0,1264.303,1336575.0,65442.2
4,4,Pakistan,Asia,65450704.0,324219.000,1130820.0,57879.0